# Módulo 1. Fundamentos de Python para investigación social computacional

**Curso:** Fundamentos de Programación para IA Generativa Aplicada  
**Orientación:** Ciencias sociales aplicadas  
**Enfoque transversal:** marxismo analítico, antropología económica y teoría matemática de las categorías

---

## Propósito del módulo

Este módulo introduce los fundamentos de Python no como una mera sintaxis instrumental, sino como un lenguaje formal para organizar, transformar e interpretar datos sociales.

En esta sesión aprenderemos a: (i)comprender qué es un objeto, una variable y un tipo de dato en Python; (ii) usar estructuras básicas para representar información social; (iii) aplicar reglas lógicas mediante condicionales, bucles y funciones; (iv) construir un primer flujo de trabajo reproducible con datos tabulares; y (vi) sentar la base computacional para el análisis posterior de módulos reales vinculados con Cusco.

---

## Idea central

Programar es **explicitar reglas de transformación**. En términos empíricos, transformamos datos. En términos conceptuales, transformamos abstracciones en operaciones. En términos categoriales, componemos funciones sobre objetos bien definidos.

## 1. Programar en ciencias sociales: una primera formulación rigurosa

En ciencias sociales, los datos no son “cosas dadas”, sino registros construidos institucionalmente. Una variable como ingreso, años de educación o participación ciudadana no agota la realidad: apenas codifica una dimensión de una relación social. Por ello, programar bien implica tres cuidados: (i) **cuidado conceptual**: saber qué representa cada variable; (ii) **cuidado lógico**: saber qué transformación estamos aplicando; y (iii) **cuidado técnico**: saber si el código respeta tipos, nombres y estructura.

Desde la teoría de categorías, podemos introducir una intuición útil desde el inicio, pues un **objeto** puede ser una tabla, una lista o una observación; un **morfismo** puede ser una función que transforma ese objeto; y un **pipeline** es una composición ordenada de funciones. Nuestro objetivo no es solo “hacer correr código”, sino construir transformaciones comprensibles, verificables y reproducibles.

In [1]:
# Configuración inicial del entorno

from __future__ import annotations

from pathlib import Path
from typing import List, Dict, Tuple, Any

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)

print("Entorno listo.")
print("Versión de pandas:", pd.__version__)
print("Versión de NumPy :", np.__version__)

Entorno listo.
Versión de pandas: 2.2.2
Versión de NumPy : 2.0.2

## 2. Objetos, variables y tipos

Una variable en Python es un nombre que referencia un objeto almacenado en memoria. Ese objeto tiene un **tipo**, y el tipo importa porque determina qué operaciones son válidas. En investigación social, esto es crucial:

- una edad puede representarse como `int`;
- un ingreso monetario como `float`;
- una categoría territorial como `str`;
- una condición lógica como `bool`.

Una mala tipificación genera errores analíticos antes incluso de que aparezcan errores estadísticos.

In [2]:
# Ejemplos básicos con sentido social

department = "Cusco"          # str
year = 2024                   # int
average_income = 1480.75      # float
is_urban = False              # bool

print("department     =", department, "| tipo:", type(department))
print("year           =", year, "| tipo:", type(year))
print("average_income =", average_income, "| tipo:", type(average_income))
print("is_urban       =", is_urban, "| tipo:", type(is_urban))

department     = Cusco | tipo: <class 'str'>
year           = 2024 | tipo: <class 'int'>
average_income = 1480.75 | tipo: <class 'float'>
is_urban       = False | tipo: <class 'bool'>

In [3]:
# Convenciones de nombres: claridad antes que brevedad

household_income = 1650.50
years_of_education = 11
participates_in_assembly = True

print("Ingreso del hogar      :", household_income)
print("Años de educación      :", years_of_education)
print("Participa en asamblea  :", participates_in_assembly)

Ingreso del hogar      : 1650.5
Años de educación      : 11
Participa en asamblea  : True

In [4]:
# Conversión de tipos y cuidado analítico

raw_income = "2350.80"
income = float(raw_income)

print("Valor original :", raw_income, "| tipo:", type(raw_income))
print("Valor convertido:", income, "| tipo:", type(income))

# Error típico: querer sumar texto y número
# print(raw_income + 10)  # Esto produciría un TypeError

Valor original : 2350.80 | tipo: <class 'str'>
Valor convertido: 2350.8 | tipo: <class 'float'>

## 3. Estructuras de datos para representar relaciones sociales

La elección de la estructura no es trivial. Cada estructura organiza la información de una forma distinta.

- **lista**: secuencia ordenada y mutable;
- **diccionario**: pares clave-valor;
- **tupla**: secuencia ordenada e inmutable;
- **conjunto**: colección sin duplicados.

Esto equivale a decidir cómo se representa formalmente una unidad de observación o una colección de observaciones.

In [5]:
# Lista: colección ordenada de observaciones simples
districts_cusco = ["Cusco", "Santiago", "San Sebastián", "San Jerónimo", "Wanchaq"]

print("Distritos:")
for district in districts_cusco:
    print("-", district)

Distritos:
- Cusco
- Santiago
- San Sebastián
- San Jerónimo
- Wanchaq

In [6]:
# Diccionario: una observación estructurada
household = {
    "hogar_id": "CUS_001",
    "distrito": "San Sebastián",
    "ingreso_mensual": 1850.0,
    "anios_educacion_jefe": 12,
    "acceso_agua_red": True
}

print("Registro del hogar:")
for key, value in household.items():
    print(f"{key}: {value}")

Registro del hogar:
hogar_id: CUS_001
distrito: San Sebastián
ingreso_mensual: 1850.0
anios_educacion_jefe: 12
acceso_agua_red: True

In [7]:
# Tupla: útil cuando la estructura no debe modificarse
coordinate_cusco = (-13.53195, -71.96746)

print("Coordenadas de referencia:", coordinate_cusco)
print("Latitud :", coordinate_cusco[0])
print("Longitud:", coordinate_cusco[1])

Coordenadas de referencia: (-13.53195, -71.96746)
Latitud : -13.53195
Longitud: -71.96746

In [8]:
# Conjunto: útil para detectar categorías únicas
educational_levels = ["Primaria", "Secundaria", "Superior", "Secundaria", "Primaria", "Superior"]
unique_levels = set(educational_levels)

print("Niveles originales :", educational_levels)
print("Niveles únicos     :", unique_levels)

Niveles originales : ['Primaria', 'Secundaria', 'Superior', 'Secundaria', 'Primaria', 'Superior']
Niveles únicos     : {'Secundaria', 'Superior', 'Primaria'}

## 4. Lógica, comparación y control de flujo

Toda clasificación social hecha en código necesita reglas explícitas. Los condicionales permiten construir esas reglas. Esto es metodológicamente importante: una tipología computacional es una decisión conceptual formalizada.

In [9]:
# Clasificación simple según ingreso mensual del hogar

household_income = 1850.0

if household_income < 1200:
    income_group = "bajo"
elif household_income < 2500:
    income_group = "medio"
else:
    income_group = "alto"

print("Ingreso del hogar:", household_income)
print("Grupo de ingreso :", income_group)

Ingreso del hogar: 1850.0
Grupo de ingreso : medio

In [10]:
# Uso de operadores lógicos

income = 1850.0
years_education = 12
has_water = True

is_relatively_stable = (income >= 1500) and (years_education >= 11) and has_water

print("¿Hogar relativamente estable?:", is_relatively_stable)

¿Hogar relativamente estable?: True

In [11]:
# Bucle: aplicar una regla a múltiples observaciones

household_incomes = [950, 1400, 2100, 3200, 1100]

for i, value in enumerate(household_incomes, start=1):
    if value < 1200:
        label = "bajo"
    elif value < 2500:
        label = "medio"
    else:
        label = "alto"
    print(f"Hogar {i}: ingreso = {value} -> grupo = {label}")

Hogar 1: ingreso = 950 -> grupo = bajo
Hogar 2: ingreso = 1400 -> grupo = medio
Hogar 3: ingreso = 2100 -> grupo = medio
Hogar 4: ingreso = 3200 -> grupo = alto
Hogar 5: ingreso = 1100 -> grupo = bajo

## 5. Funciones: de la intuición a la formalización

Una función recibe entradas, aplica una regla y devuelve una salida. Es decir, hay un dominio de entrada; hay una regla de transformación; y hay un codominio de salida. En programación, una función bien escrita: hace una sola cosa; tiene entradas claras; devuelve una salida interpretable; y puede reutilizarse y verificarse.

In [12]:
def classify_income(income: float) -> str:
    """
    Clasifica el ingreso mensual del hogar en tres grupos.

    Parámetros
    ----------
    income : float
        Ingreso mensual del hogar.

    Retorna
    -------
    str
        Etiqueta: 'bajo', 'medio' o 'alto'.
    """
    if income < 1200:
        return "bajo"
    elif income < 2500:
        return "medio"
    return "alto"


print(classify_income(900))
print(classify_income(1800))
print(classify_income(3200))

bajo
medio
alto

In [16]:
def household_profile(income: float, education: int, water_access: bool) -> Dict[str, Any]:
    """
    Construye un perfil simplificado del hogar.
    """
    return {
        "income": income,
        "income_group": classify_income(income),
        "years_education": education,
        "water_access": water_access,
        "educational_threshold_met": education >= 11
    }


example_profile = household_profile(1850.0, 12, True)
example_profile
example_profile_1 = household_profile(800.0, 10, False)
example_profile_1

{'income': 800.0,
 'income_group': 'bajo',
 'years_education': 10,
 'water_access': False,
 'educational_threshold_met': False}

## 6. Primer paso hacia datos tabulares

Las encuestas y registros administrativos suelen representarse como tablas: filas y columnas. Una **fila** representa una unidad de observación; una **columna** representa una variable; y una **tabla** organiza sistemáticamente múltiples observaciones. Para nosotros, la tabla será una estructura central porque la Tarea 1 requerirá trabajar con módulos reales de datos.

In [17]:
# Microdataset didáctico: hogares de Cusco
data = {
    "hogar_id": ["CUS_001", "CUS_002", "CUS_003", "CUS_004", "CUS_005"],
    "departamento": ["Cusco", "Cusco", "Cusco", "Cusco", "Cusco"],
    "anio": [2021, 2022, 2023, 2024, 2024],
    "ingreso_mensual": [980.0, 1450.0, 1750.0, 2100.0, 3100.0],
    "anios_educacion_jefe": [8, 11, 12, 14, 16],
    "participacion_ciudadana": [0, 1, 1, 0, 1],
    "acceso_agua_red": [True, True, True, False, True]
}

df = pd.DataFrame(data)
df

  hogar_id departamento  anio  ingreso_mensual  anios_educacion_jefe  participacion_ciudadana  acceso_agua_red
0  CUS_001        Cusco  2021            980.0                     8                        0             True
1  CUS_002        Cusco  2022           1450.0                    11                        1             True
2  CUS_003        Cusco  2023           1750.0                    12                        1             True
3  CUS_004        Cusco  2024           2100.0                    14                        0            False
4  CUS_005        Cusco  2024           3100.0                    16                        1             True

In [18]:
# Inspección mínima rigurosa

print("Forma de la tabla:", df.shape)
print("\nTipos de datos:")
print(df.dtypes)

print("\nValores faltantes:")
print(df.isna().sum())

print("\nVista general:")
display(df.head())

Forma de la tabla: (5, 7)

Tipos de datos:
hogar_id                    object
departamento                object
anio                         int64
ingreso_mensual            float64
anios_educacion_jefe         int64
participacion_ciudadana      int64
acceso_agua_red               bool
dtype: object

Valores faltantes:
hogar_id                   0
departamento               0
anio                       0
ingreso_mensual            0
anios_educacion_jefe       0
participacion_ciudadana    0
acceso_agua_red            0
dtype: int64

Vista general:

  hogar_id departamento  anio  ingreso_mensual  anios_educacion_jefe  participacion_ciudadana  acceso_agua_red
0  CUS_001        Cusco  2021            980.0                     8                        0             True
1  CUS_002        Cusco  2022           1450.0                    11                        1             True
2  CUS_003        Cusco  2023           1750.0                    12                        1             True
3  CUS_004        Cusco  2024           2100.0                    14                        0            False
4  CUS_005        Cusco  2024           3100.0                    16                        1             True

In [19]:
# Enriquecer la tabla con funciones definidas por nosotros

df["grupo_ingreso"] = df["ingreso_mensual"].apply(classify_income)
df["educacion_alta"] = df["anios_educacion_jefe"] >= 11

display(df)

,hogar_id,departamento,anio,ingreso_mensual,anios_educacion_jefe,participacion_ciudadana,acceso_agua_red,grupo_ingreso,educacion_alta
0,CUS_001,Cusco,2021,980.0,8,0,True,bajo,False
1,CUS_002,Cusco,2022,1450.0,11,1,True,medio,True
2,CUS_003,Cusco,2023,1750.0,12,1,True,medio,True
3,CUS_004,Cusco,2024,2100.0,14,0,False,medio,True
4,CUS_005,Cusco,2024,3100.0,16,1,True,alto,True

In [20]:
# Primeras preguntas analíticas

mean_income = df["ingreso_mensual"].mean()
share_high_education = df["educacion_alta"].mean()
share_participation = df["participacion_ciudadana"].mean()

print(f"Ingreso promedio del microdataset: {mean_income:.2f}")
print(f"Proporción con educación >= 11 años: {share_high_education:.2%}")
print(f"Proporción con participación ciudadana: {share_participation:.2%}")

Ingreso promedio del microdataset: 1876.00
Proporción con educación >= 11 años: 80.00%
Proporción con participación ciudadana: 60.00%

In [21]:
# Filtrado: ¿qué hogares combinan menor ingreso y menor escolaridad?

subset = df[
    (df["ingreso_mensual"] < 1800) &
    (df["anios_educacion_jefe"] < 11)
]

display(subset)

,hogar_id,departamento,anio,ingreso_mensual,anios_educacion_jefe,participacion_ciudadana,acceso_agua_red,grupo_ingreso,educacion_alta
0,CUS_001,Cusco,2021,980.0,8,0,True,bajo,False

## 7. Interpretación social mínima

Incluso en un ejemplo didáctico, no debemos confundir descripción con explicación. Que un hogar presente menor ingreso y menor escolaridad no “demuestra” por sí mismo un mecanismo causal. Lo que sí hace el código es permitirnos: organizar observaciones; construir reglas de clasificación; describir distribuciones; y preparar el terreno para análisis más rigurosos. Ese paso intermedio es fundamental: antes de inferir, hay que estructurar correctamente los datos.

## 8. Ejercicio aplicado

Replica el flujo anterior cambiando dos cosas: (i) redefine la función de clasificación de ingreso con otros umbrales; y (ii) agrega una nueva variable binaria que indique si el hogar combina: ingreso menor al promedio, menos de 11 años de educación, y ausencia de acceso a agua por red. Y respondamos ¿cuántos hogares cumplen simultáneamente esas condiciones? ¿qué límites tiene este ejercicio si solo usamos un microdataset didáctico?

## 9. Cierre del módulo

En esta sesión hemos establecido la base del curso:

- objetos y tipos;
- estructuras de datos;
- lógica y control de flujo;
- funciones;
- primera manipulación tabular con `pandas`.

### Puente hacia la Tarea 1

Más adelante reemplazaremos este microdataset por módulos reales.  
Entonces, estas mismas operaciones servirán para: cargar bases reales; seleccionar Cusco; limpiar variables; construir indicadores; y formular una primera pregunta empírica consistente con el trabajo final. La sesión 1 no agota el análisis; prepara su forma.